# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  application: YoFi.AspNet
  tests: YoFi.Tests

steps:
- checkout: self
  submodules: true

- task: CmdLine@2
  inputs:
    script: 'git describe --long --always --abbrev=8 > $(application)/version.txt'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(application)/$(application).csproj'
    arguments: '--output $(System.DefaultWorkingDirectory)/publish_output --configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(tests)/$(tests).csproj'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop